const $ = (s) => document.querySelector(s); let activeTab; let state = { activeTopic: '', captures: [] };
const validUrl = (url = '') => /^https?:\/\//.test(url); const topicCaptures = () => state.captures.filter((c) => c.topic === state.activeTopic);
const esc = (v = '') => v.replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
function render() { const hasTopic = !!state.activeTopic, captures = topicCaptures(); $('#currentTopic').textContent = hasTopic ? state.activeTopic : 'Choose a topic'; $('#topicForm').classList.toggle('expanded', !hasTopic); $('#pageCard').classList.toggle('hidden', !hasTopic || !activeTab || !validUrl(activeTab.url)); $('#clearTopic').style.visibility = captures.length ? 'visible' : 'hidden'; $('#itemCount').textContent = `${captures.length} source${captures.length === 1 ? '' : 's'}`; $('#progressFill').style.width = `${Math.min(captures.length * 20, 100)}%`; $('#progressText').textContent = captures.length ? `${captures.length} source${captures.length === 1 ? ' is' : 's are'} shaping this roadmap.` : 'Your first source will become the starting point.'; if (activeTab && validUrl(activeTab.url)) { $('#pageTitle').textContent = activeTab.title || 'Untitled page'; $('#pageUrl').textContent = new URL(activeTab.url).hostname.replace(/^www\./, ''); } $('#recentList').innerHTML = captures.length ? captures.slice(0, 4).map((c, i) => `<article class="recent-item"><span class="step">${i + 1}</span><div><h3>${esc(c.title)}</h3><p>${esc(c.summary)}</p></div></article>`).join('') : '<p class="empty-state">Nothing saved yet. Explore a page to begin.</p>'; }
async function load() { state = await chrome.storage.local.get({ activeTopic: '', captures: [] }); [activeTab] = await chrome.tabs.query({ active: true, currentWindow: true }); render(); }
$('#saveTopic').onclick = async () => { const topic = $('#topicInput').value.trim(); if (!topic) return $('#topicInput').focus(); state.activeTopic = topic; await chrome.storage.local.set({ activeTopic: topic }); $('#topicInput').value = ''; $('#status').textContent = `Capturing useful reads about ${topic}.`; render(); };
$('#editTopic').onclick = () => { $('#topicForm').classList.add('expanded'); $('#topicInput').focus(); };
$('#saveNow').onclick = async () => { if (!activeTab || !validUrl(activeTab.url)) return; $('#saveNow').textContent = 'Saving…'; try { await chrome.runtime.sendMessage({ type: 'CAPTURE_NOW', tabId: activeTab.id }); $('#saveNow').textContent = 'Saved ✓'; setTimeout(() => { $('#saveNow').textContent = 'Save to this thread'; load(); }, 900); } catch { $('#saveNow').textContent = 'Couldn’t save'; } };
$('#clearTopic').onclick = async () => { state.captures = state.captures.filter((c) => c.topic !== state.activeTopic); await chrome.storage.local.set({ captures: state.captures }); render(); }; $('#openDashboard').onclick = () => chrome.tabs.create({ url: chrome.runtime.getURL('dashboard.html') }); chrome.storage.onChanged.addListener(load); load();
